[package]
name = "rust_ed420"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
sha2 = "0.10"
rand = "0.8"
lazy_static = "1.4.0"
